---
- name: Common Play for all instances
  hosts: "{{ variable_host }}"
  remote_user: ansible
  become: yes
  become_user: root
  tags:
    - baseplay
  roles:
    - common
    
- name: Play for Web Server
  hosts: "{{ variable_host }}"
  remote_user: ansible
  become: yes
  become_user: root
  tags:
    - webserver
  roles:
    - common
    - web

- name: Play for DB Server
  hosts: "{{ variable_host }}"
  remote_user: ansible
  become: yes
  become_user: root
  tags:
    - dbserver
  roles:
    - common
    - db
